DROP INDEX post_employee_idx;
DROP INDEX post_role_idx;
DROP INDEX post_department_idx;
DROP INDEX robot_operator_idx;
DROP INDEX robot_asteroid_idx;
DROP INDEX asteroid_distance_idx;
DROP TABLE "robot" CASCADE;
DROP TABLE "positronic_brain" CASCADE;
DROP TABLE "body" CASCADE;
DROP TABLE "eyes_sensors" CASCADE;
DROP TABLE "task" CASCADE;
DROP TABLE "role" CASCADE;
DROP TABLE "employee" CASCADE;
DROP TABLE "asteroid" CASCADE;
DROP TABLE "deposit" CASCADE;
DROP TABLE "microreactor_type" CASCADE;
DROP TABLE "microreactor_in_spaceship" CASCADE;
DROP TABLE "spaceship" CASCADE;
DROP TABLE "post"  CASCADE;
DROP TABLE "department" CASCADE;